=== NYPL/ami-metadata/versions/x.0/schema/digitized_audioreeldigital.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "AMI Vendor Audio Digital Reel Schema",
  "id": "digitized_audioreeldigital",
  "description": "Definitions for audio digital reel fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "id": "technical",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "filename",
        "extension",
        "fileFormat",
        "fileSize",
        "durationHuman"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
          "$ref": "fields#technicalExtensionForAudio"
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "$ref": "fields#technicalFileFormatForAudio"
        },
        "audioCodec": {
          "$ref": "fields#technicalAudioCodecForAudio"
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        },
        "signalNotes": {
          "$ref": "fields#technicalSignalNotes"
        },
        "audioBitDepth": {
          "$ref": "fields#technicalAudioBitDepth"
        },
        "audioBitRate": {
          "$ref": "fields#technicalAudioBitRate"
        },
        "audioCodecVersion": {
          "$ref": "fields#technicalAudioCodecVersion"
        },
        "audioDataEncoding": {
          "$ref": "fields#technicalAudioDataEncoding"
        },
        "audioSamplingRate": {
          "$ref": "fields#technicalAudioSamplingRate"
        }
      }
    },
    "source": {
      "id": "source",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "object",
        "subObject"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "audio reel digital" ]
            },
            "format": {
              "enum": [
                "ProDigi",
                "DASH",
                "NAGRA-D",
                "unknown"
              ]
            },
            "generation": {
              "type": "string"
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "subObject": {
          "$ref": "fields#subObjectWithStreams"
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "diameter": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.25
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "stockLength": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 1.0
                },
                "unit": {
                  "enum": [
                    "min"
                  ]
                }
              }
            },
            "stockProductID": {
              "type": "string"
            },
            "stockManufacturer": {
              "type": "string"
            },
            "tapeWidth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    0.25,
                    0.5,
                    1,
                    2
                  ]
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "tapeThickness": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.01
                },
                "unit": {
                  "enum": [
                    "mils"
                  ]
                }
              }
            },
            "baseMaterial": {
              "enum": [
                "polyester",
                "acetate",
                "acetate and polyester"
              ]
            },
            "backcoatMaterial": {
              "enum": [
                "yes",
                "no"
              ]
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "audioSoundField": {
              "enum": [
                "stereo",
                "mono",
                "unknown",
                "multitrack"
              ]
            },
            "numberOfAudioTracks": {
              "enum": [
                1,
                2,
                3,
                4,
                8,
                16,
                24,
                32,
                48,
                "n/a",
                "unknown"
              ]
            },
            "designatedSpeed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    45,
                    30,
                    27.56,
                    26.95,
                    15,
                    7.5,
                    3.75,
                    1.875,
                    "unknown"
                  ]
                },
                "unit": {
                  "enum": [
                    "ips"
                  ]
                }
              }
            },
            "audioBitDepth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    8,
                    16,
                    18,
                    20,
                    24,
                    32
                  ]
                },
                "unit": {
                  "enum": [
                    "bit"
                  ]
                }
              }
            },
            "audioSamplingRate": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    22500,
                    32000,
                    44056,
                    44100,
                    47925,
                    48000,
                    64000,
                    88000,
                    88112,
                    88200,
                    95904,
                    96000,
                    128000,
                    176224,
                    176400,
                    191808,
                    192000
                  ]
                },
                "unit": {
                  "enum": [
                    "hz"
                  ]
                }
              }
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id":  {
              "$ref": "fields#playbackDeviceID"
            },
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            },
            "speed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    45,
                    30,
                    27.56,
                    26.95,
                    15,
                    7.5,
                    3.75,
                    1.875
                  ]
                },
                "unit": {
                  "enum": [
                    "ips"
                  ]
                }
              }
            }
          }
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "takeNumber": {
          "$ref": "fields#takeNumber"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/versions/1.1/sample/sample_digitized_audioreeldigital.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.wav",
		"fileRole": "pm",
		"schemaVersion": "1.1.0"
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myh",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Dance Audio 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "myh_abc123_v01_pm",
		"extension": "wav",
		"dateCreated": "2016-01-01",
		"fileFormat": "BWF",
		"audioCodec": "PCM",
		"fileSize": {
			"measure": 2000000000,
			"unit": "B"
		},
		"durationMilli": {
			"measure": 3600000,
			"unit": "ms"
		},
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio reel digital",
			"format": "ProDigi",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 2,
			"streamNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"diameter": {
				"measure": 7,
				"unit": "in"
			},
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": {
				"measure": 0.25,
				"unit": "in"
			},
			"tapeThickness": {
				"measure": 1.5,
				"unit": "mils"
			},
			"baseMaterial": "polyester",
			"backcoatMaterial": "yes"
		},
		"audioRecording": {
			"audioSoundField": "multitrack",
			"numberOfAudioTracks": 48,
			"designatedSpeed": {
				"measure": 3.75,
				"unit": "ips"
			},
			"audioBitDepth": {
				"measure": 24,
				"unit": "bit"
			},
			"audioSamplingRate": {
				"measure": 22500,
				"unit": "hz"
			}
		},
		"notes": {
			"physicalConditionPreShipNotes": "reel show XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows XYZ damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"speed": {
				"measure": 7.5,
				"unit": "ips"
			}
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
