=== NYPL/ami-metadata/versions/2.0/schema/digitized_videocassettedigital.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Digitized Digital Video Cassette Schema",
  "$id": "digitized_videocassettedigital",
  "description": "Definitions for digital video cassette fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "$id": "technical",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "filename",
        "extension",
        "dateCreated",
        "fileFormat",
        "audioCodec",
        "videoCodec",
        "fileSize",
        "durationMilli",
        "durationHuman"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
            "enum": [
              "mkv", "MKV",
              "mp4", "MP4",
              "dv", "DV"
            ]
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "$ref": "fields#technicalFileFormat"
        },
        "audioCodec": {
          "$ref": "fields#technicalAudioCodecForVideo"
        },
        "videoCodec": {
          "enum": [
            "DV",
            "dvc",
            "dvh3",
            "dvh6",
            "dvhp",
            "dvhq",
            "hdv2",
            "hdv6",
            "xd5f",
            "xdv2",
            "xdvb",
            "xdvd",
            "H264",
            "h264",
            "ffv1",
            "FFV1",
            "AVC",
            "avc"
          ]
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        },
        "signalNotes": {
          "$ref": "fields#technicalSignalNotes"
        }
      }
    },
    "source": {
      "$id": "source",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "object",
        "physicalDescription",
        "contentSpecifications",
        "audioRecording"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [
                "video cassette digital"
              ]
            },
            "format": {
              "enum": [
                "Betacam SX",
                "D-1",
                "D-2",
                "D-3",
                "D-5",
                "D-9",
                "Digital Betacam",
                "Digital8",
                "DVCam",
                "DVCPRO",
                "DVCPRO 5",
                "DVCPRO 50",
                "DVCPRO HD",
                "HDCAM",
                "HDCAM SR",
                "HDV",
                "MiniDV",
                "MPEG IMX"
              ]
            },
            "generation": {
              "type": "string"
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0,
              "minimum": 1
            }
          }
        },
        "subObject": {
          "$ref": "fields#subObjectWithoutStreams"
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "stockManufacturer",
            "tapeWidth",
            "oxideMaterial"
          ],
          "properties": {
            "stockLength": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.1,
                  "minimum": 0.1
                },
                "unit": {
                  "enum": [
                    "min"
                  ]
                }
              }
            },
            "stockManufacturer": {
              "type": "string"
            },
            "stockProductID": {
              "type": "string"
            },
            "tapeWidth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.01,
                  "minimum": 0
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "baseMaterial": {
              "enum": [
                "polyester",
                "unknown"
              ]
            },
            "oxideMaterial": {
              "enum": [
                "ferric oxide",
                "chromium dioxide",
                "unknown"
              ]
            }
          }
        },
        "contentSpecifications": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "broadcastStandard",
            "colorBW"
          ],
          "properties": {
            "broadcastStandard": {
              "enum": [
                "NTSC",
                "PAL",
                "SECAM",
                "1080i",
                "1080p",
                "720p"
              ]
            },
            "colorBW": {
              "enum": [
                "b/w",
                "color",
                "color & b/w"
              ]
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "audioSoundField",
            "numberOfAudioTracks"
          ],
          "properties": {
            "audioSoundField": {
              "$ref": "fields#audioSoundFieldForVideo"
            },
            "numberOfAudioTracks": {
              "type": "number",
              "multipleOf": 1.0,
              "minimum": 0
            },
            "audioBitDepth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    8,
                    16,
                    18,
                    20,
                    24,
                    32,
                    48
                  ]
                },
                "unit": {
                  "enum": [
                    "bit"
                  ]
                }
              }
            },
            "audioSamplingRate": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    22500,
                    32000,
                    44056,
                    44100,
                    47925,
                    48000,
                    64000,
                    88000,
                    88112,
                    88200,
                    95904,
                    96000,
                    128000,
                    176224,
                    176400,
                    191808,
                    192000
                  ]
                },
                "unit": {
                  "enum": [
                    "hz"
                  ]
                }
              }
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "$id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            }
          }
        },
        "timeBaseCorrector": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "serialNumber": {
              "$ref": "fields#timeBaseCorrectorSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#timeBaseCorrectorManufacturer"
            },
            "model": {
              "$ref": "fields#timeBaseCorrectorModel"
            }
          }
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "takeNumber": {
          "$ref": "fields#takeNumber"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/versions/2.0/sample/sample_digitized_videocassettedigital.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.mov",
		"fileRole": "pm",
		"schemaVersion": "2.0.0"
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myh",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Dance Video 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Video 2 instead of Dance Video 1"
	},
	"technical": {
		"filename": "myh_abc123_v01_pm",
		"extension": "mkv",
		"dateCreated": "2017-07-01",
		"fileFormat": "MKV file",
		"audioCodec": "PCM",
		"videoCodec": "FFV1",
		"fileSize": {
			"measure": 30000000000,
			"unit": "B"
		},
		"durationMilli": {
			"measure": 3600000,
			"unit": "ms"
		},
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "video cassette digital",
			"format": "DVCPRO",
			"volumeNumber": 1
		},
		"physicalDescription": {
			"stockLength": {
				"measure": 60,
				"unit": "min"
			},
			"stockManufacturer": "Panasonic",
			"stockProductID": "DVC-30",
			"tapeWidth": {
				"measure": 0.25,
				"unit": "in"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "unknown"
		},
		"contentSpecifications": {
			"broadcastStandard": "SECAM",
			"colorBW": "b/w"
		},
		"audioRecording": {
			"audioSoundField": "mono",
			"numberOfAudioTracks": 1,
			"audioBitDepth": {
				"measure": 48,
				"unit": "bit"
			},
			"audioSamplingRate": {
				"measure": 22500,
				"unit": "hz"
			}
		},
		"notes": {
			"physicalConditionPreShipNotes": "cassette shows XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
