=== NYPL/ami-metadata/versions/2.0/schema/digitized_videocassetteanalog.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Digitized Video Cassette Schema",
  "id": "digitized_videocassetteanalog",
  "description": "Definitions for audio optical fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "id": "technical",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "filename",
        "extension",
        "dateCreated",
        "fileFormat",
        "audioCodec",
        "videoCodec",
        "fileSize",
        "durationMilli",
        "durationHuman"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
          "$ref": "fields#technicalExtensionForVideo"
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "$ref": "fields#technicalFileFormat"
        },
        "audioCodec": {
          "$ref": "fields#technicalAudioCodecForVideo"
        },
        "videoCodec": {
          "$ref": "fields#technicalVideoCodecForVideo"
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        },
        "signalNotes": {
          "$ref": "fields#technicalSignalNotes"
        }
      }
    },
    "source": {
      "id": "source",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "object",
        "physicalDescription",
        "contentSpecifications",
        "audioRecording"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "video cassette analog" ]
            },
            "format": {
              "enum": [
                "Betacam",
                "Betacam SP",
                "Betamax",
                "Hi8",
                "MII",
                "S-VHS",
                "S-VHS-C",
                "U-matic",
                "U-matic S",
                "U-matic SP",
                "VHS",
                "VHS-C",
                "Video8"
              ]
            },
            "generation": {
              "type": "string"
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "subObject": {
          "$ref": "fields#subObjectWithoutStreams"
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "stockManufacturer",
            "tapeWidth",
            "oxideMaterial"
          ],
          "properties": {
            "stockLength": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 1.0
                },
                "unit": {
                  "enum": [
                    "min"
                  ]
                }
              }
            },
            "stockManufacturer": {
              "type": "string"
            },
            "stockProductID": {
              "type": "string"
            },
            "tapeWidth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.01
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "baseMaterial": {
              "enum": [
                "acetate",
                "polyester",
                "acetate and polyester",
                "unknown"
              ]
            },
            "oxideMaterial": {
              "enum": [
                "ferric oxide",
                "chromium dioxide",
                "unknown"
              ]
            }
          }
        },
        "contentSpecifications": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "broadcastStandard",
            "colorBW"
          ],
          "properties": {
            "broadcastStandard": {
              "enum": [
                "NTSC",
                "PAL",
                "SECAM"
              ]
            },
            "colorBW": {
              "enum": [
                "b/w",
                "color",
                "color & b/w"
              ]
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "audioSoundField",
            "numberOfAudioTracks"
          ],
          "properties": {
            "audioSoundField": {
              "$ref": "fields#audioSoundFieldForVideo"
            },
            "numberOfAudioTracks": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "timeBaseCorrector",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#playbackDeviceID"
            },
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            }
          }
        },
        "timeBaseCorrector": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#timeBaseCorrectorID"
            },
            "serialNumber": {
              "$ref": "fields#timeBaseCorrectorSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#timeBaseCorrectorManufacturer"
            },
            "model": {
              "$ref": "fields#timeBaseCorrectorModel"
            }
          }
        },
        "analogDigitalConverter": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#analogDigitalConverterID"
            },
            "serialNumber": {
              "$ref": "fields#analogDigitalConverterSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#analogDigitalConverterManufacturer"
            },
            "model": {
              "$ref": "fields#analogDigitalConverterModel"
            }
          }
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "takeNumber": {
          "$ref": "fields#takeNumber"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/versions/2.0/sample/sample_digitized_videocassetteanalog.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.mov",
		"fileRole": "pm",
		"schemaVersion": "2.0.0"
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myh",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Dance Video 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Video 2 instead of Dance Video 1"
	},
	"technical": {
		"filename": "myh_abc123_v01_pm",
		"extension": "mkv",
		"dateCreated": "2017-07-01",
		"fileFormat": "MKV file",
		"audioCodec": "FLAC",
		"videoCodec": "FFV1",
		"fileSize": {
			"measure": 100000000000,
			"unit": "B"
		},
		"durationMilli": {
			"measure": 3600000,
			"unit": "ms"
		},
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "video cassette analog",
			"format": "Hi8",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"stockLength": {
				"measure": 60,
				"unit": "min"
			},
			"stockManufacturer": "Sony",
			"stockProductID": "KCA-60",
			"tapeWidth": {
				"measure": 0.314,
				"unit": "in"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "ferric oxide"
		},
		"contentSpecifications": {
			"broadcastStandard": "SECAM",
			"colorBW": "b/w"
		},
		"audioRecording": {
			"audioSoundField": "Ch1: Mono; Ch2: None; Ch3: Mono; Ch4: None",
			"numberOfAudioTracks": 1
		},
		"notes": {
			"physicalConditionPreShipNotes": "cassette shows XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ"
		},
		"timeBaseCorrector": {
			"serialNumber": "12345",
      "manufacturer": "Manufacturer C",
      "model": "Model XYZ"
		},
		"analogDigitalConverter" : {
      "serialNumber": "id12345abc",
      "manufacturer": "Manufacturere D",
      "model": "Model XYZ"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
