=== NYPL/ami-metadata/versions/2.0/schema/digitized_dataopticaldisc.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Digitized Data Optical Disc Schema",
  "$id": "digitized_videoopticaldisc",
  "description": "Definitions for video optical fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "$id": "technical",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "filename",
        "extension",
        "dateCreated",
        "fileFormat",
        "fileSize"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
          "enum": [
            "iso", "ISO"
          ]
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "$ref": "fields#technicalFileFormat"
        },
        "videoCodec": {
          "enum": [
            "ISO 9660"
          ]
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        }
      }
    },
    "source": {
      "$id": "source",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "object",
        "physicalDescription"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "data optical disc" ]
            },
            "format": {
              "enum": [
                "DVD-R",
                "DVD, pressed",
                "DVD+R",
                "DVD+RW",
                "DVD-RAM",
                "CD-R",
                "CD+R",
                "CD-RW",
                "CD_ROM"
              ]
            },
            "generation": {
              "type": "string"
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0,
              "minimum": 1
            }
          }
        },
        "subObject": {
          "$ref": "fields#subObjectWithoutStreams"
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "stockManufacturer",
            "diameter",
            "dyeLayer",
            "reflectiveLayer"
          ],
          "properties": {
            "stockManufacturer": {
              "type": "string"
            },
            "diameter": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    4.7,
                    3.1,
                    12
                  ]
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "dyeLayer": {
              "enum": [
                "phthalocyanine",
                "cyanine",
                "azo",
                "unknown"
              ]
            },
            "reflectiveLayer": {
              "enum": [
                "gold",
                "silver",
                "aluminum",
                "unknown"
              ]
            },
            "dataCapacity": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    0.7,
                    4.7,
                    1.4,
                    8.54,
                    25,
                    50,
                    "unknown"
                  ]
                },
                "unit": {
                  "enum": [
                    "GB"
                  ]
                }
              }
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "$id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            }
          }
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/versions/2.0/sample/sample_digitized_dataopticaldisc.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.iso",
		"fileRole": "sc",
		"schemaVersion": "2.0.0"
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSItemID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myh",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Super Fun Party Mix 1999",
		"date": "1999",
		"contentNotes": "Jane Doe's Mix CD files"
	},
	"technical": {
		"filename": "myh_abc123_v01_pm",
		"extension": "iso",
		"dateCreated": "2017-07-01",
		"fileFormat": "ISO image",
		"fileSize": {
			"measure": 100000000000,
			"unit": "B"
		}
	},
	"source": {
		"object": {
			"type": "data optical disc",
			"format": "CD-R",
			"generation": "Archive Original",
			"volumeNumber": 1
		},
		"physicalDescription": {
			"stockManufacturer": "Manufacturer A",
			"diameter": {
				"measure": 4.7,
				"unit": "in"
			},
			"dyeLayer": "phthalocyanine",
			"reflectiveLayer": "silver",
			"dataCapacity": {
				"measure": 4.7,
				"unit": "GB"
			}
		},
		"notes": {
			"physicalConditionPreShipNotes": "disc scratched",
			"physicalConditionDigitizationNotes": "damage may have impacted ISO"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "Described as audio CD in inventory but actually contained MP3s and JPGs"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
