=== NYPL/ami-metadata/versions/2.0/schema/digitized_audioopticaldisc.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Digitized Audio Optical Disc Schema",
  "id": "digitized_audioopticaldisc",
  "description": "Definitions for audio optical fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "id": "technical",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "filename",
        "extension",
        "dateCreated",
        "fileFormat",
        "audioCodec",
        "fileSize",
        "durationMilli",
        "durationHuman",
        "cueFilename"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
          "$ref": "fields#technicalExtensionForAudio"
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "$ref": "fields#technicalFileFormatForAudio"
        },
        "audioCodec": {
          "$ref": "fields#technicalAudioCodecForAudio"
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        },
        "signalNotes": {
          "$ref": "fields#technicalSignalNotes"
        },
        "cueFilename" : {
            "type": "string",
            "pattern": "^[a-zA-Z\\d\\-\\*]+"
        }
      }
    },
    "source": {
      "id": "source",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "object",
        "subObject",
        "physicalDescription",
        "audioRecording"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "audio optical disc" ]
            },
            "format": {
              "enum": [
                "Audio CD-R",
                "Audio CD, pressed",
                "Minidisc"
              ]
            },
            "generation": {
              "type": "string"
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "subObject": {
          "$ref": "fields#subObjectWithoutStreams"
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "stockManufacturer",
            "diameter"
          ],
          "properties": {
            "stockManufacturer": {
              "type": "string"
            },
            "diameter": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    4.7,
                    3.1
                  ]
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "dyeLayer": {
              "enum": [
                "phthalocyanine",
                "cyanine",
                "azo",
                "unknown"
              ]
            },
            "reflectiveLayer": {
              "enum": [
                "gold",
                "silver",
                "aluminum",
                "unknown"
              ]
            },
            "dataCapacity": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    155,
                    185,
                    210,
                    650,
                    700,
                    "unknown"
                  ]
                },
                "unit": {
                  "enum": [
                    "MiB"
                  ]
                }
              }
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "audioSoundField"
          ],
          "properties": {
            "audioSoundField": {
              "enum": [
                "stereo",
                "mono",
                "surround",
                "quadrophonic",
                "binaural",
                "unknown"
              ]
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#playbackDeviceID"
            },
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            }
          }
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/versions/2.0/sample/sample_digitized_audioopticaldisc.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.wav",
		"fileRole": "pm",
		"schemaVersion": "2.0.0"
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myh",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Dance Audio 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "myh_abc123_v01_pm",
		"cueFilename": "myh_abc123_v01_pm.cue",
		"extension": "wav",
		"dateCreated": "2017-07-01",
		"fileFormat": "BWF",
		"audioCodec": "PCM",
		"fileSize": {
			"measure": 2000000000,
			"unit": "B"
		},
		"durationMilli": {
			"measure": 3600000,
			"unit": "ms"
		},
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio optical disc",
			"format": "Audio CD-R",
			"generation": "Archive Original",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"stockManufacturer": "Manufacturer A",
			"diameter": {
				"measure": 4.7,
				"unit": "in"
			},
			"dyeLayer": "phthalocyanine",
			"reflectiveLayer": "silver"
		},
		"audioRecording": {
			"audioSoundField": "stereo"
		},
		"notes": {
			"physicalConditionPreShipNotes": "disc shows XYZ damage",
			"physicalConditionDigitizationNotes": "medium shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
