=== NYPL/ami-metadata/versions/2.0/schema/digitized_audiocassettedigital.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "AMI Vendor Audio Digital Cassette Schema",
  "$id": "digitized_audiocassettedigital",
  "description": "Definitions for audio digital cassette fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "$id": "technical",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "filename",
        "extension",
        "dateCreated",
        "fileFormat",
        "audioCodec",
        "fileSize",
        "durationMilli",
        "durationHuman"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
          "$ref": "fields#technicalExtensionForAudio"
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "$ref": "fields#technicalFileFormatForAudio"
        },
        "audioCodec": {
          "$ref": "fields#technicalAudioCodecForAudio"
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        },
        "signalNotes": {
          "$ref": "fields#technicalSignalNotes"
        }
      }
    },
    "source": {
      "$id": "source",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "object",
        "subObject",
        "physicalDescription",
        "audioRecording"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "audio cassette digital" ]
            },
            "format": {
              "enum": [
                "ADAT",
                "DAT",
                "DA-88",
                "Digital Compact Cassette",
                "Betamax/PCM",
                "U-matic/PCM",
                "VHS/PCM",
                "Hi8/PCM"
              ]
            },
            "generation": {
              "type": "string"
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0,
              "minimum": 1
            }
          }
        },
        "subObject": {
          "$ref": "fields#subObjectWithStreams"
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "tapeWidth",
            "oxideMaterial"
          ],
          "properties": {
            "stockLength": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 1.0,
                  "minimum": 1
                },
                "unit": {
                  "enum": [
                    "min"
                  ]
                }
              }
            },
            "stockProductID": {
              "type": "string"
            },
            "stockManufacturer": {
              "type": "string"
            },
            "tapeWidth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    0.125,
                    0.75,
                    0.5,
                    0.25,
                    0.15,
                    8
                  ]
                },
                "unit": {
                  "enum": [
                    "in",
                    "mm"
                  ]
                }
              }
            },
            "tapeThickness": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.5,
                  "minimum": 1
                },
                "unit": {
                  "enum": [
                    "mils"
                  ]
                }
              }
            },
            "baseMaterial": {
              "enum": [
                "acetate",
                "polyester",
                "acetate and polyester",
                "PVC",
                "unknown"
              ]
            },
            "oxideMaterial": {
              "enum": [
                "ferric oxide",
                "chromium dioxide",
                "ferrichrome",
                "metal oxide",
                "unknown"
              ]
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "audioSoundField",
            "numberOfAudioTracks",
            "trackConfiguration",
            "designatedSpeed",
            "audioBitDepth",
            "audioSamplingRate"
          ],
          "properties": {
            "audioSoundField": {
              "enum": [
                "stereo",
                "mono",
                "surround",
                "quadrophonic",
                "binaural",
                "multi-track"
              ]
            },
            "numberOfAudioTracks": {
              "enum": [
                1,
                2,
                4,
                8,
                16,
                32
              ]
            },
            "trackConfiguration": {
              "enum": [
                "full-track",
                "half-track",
                "quarter-track",
                "2 track",
                "4 track",
                "helical",
                "multi-track"
              ]
            },
            "designatedSpeed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    0.3209,
                    0.16043,
                    0.787,
                    3.75,
                    1.313,
                    1.575,
                    1.875,
                    0.63,
                    14.3,
                    "none"
                  ]
                },
                "unit": {
                  "enum": [
                    "ips",
                    "mm/s"
                  ]
                }
              }
            },
            "audioBitDepth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    8,
                    16,
                    18,
                    20,
                    24,
                    32
                  ]
                },
                "unit": {
                  "enum": [
                    "bit"
                  ]
                }
              }
            },
            "audioSamplingRate": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    22500,
                    32000,
                    44056,
                    44100,
                    47925,
                    48000,
                    64000,
                    88000,
                    88112,
                    88200,
                    95904,
                    96000,
                    128000,
                    176224,
                    176400,
                    191808,
                    192000
                  ]
                },
                "unit": {
                  "enum": [
                    "hz"
                  ]
                }
              }
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "$id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model",
            "speed"
          ],
          "properties": {
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            },
            "eq": {
              "enum": [
                "with pre-emphasis",
                "without pre-emphasis"
              ]
            },
            "speed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    0.3209,
                    0.16043,
                    3.75,
                    1.875,
                    0.63,
                    14.3
                  ]
                },
                "unit": {
                  "enum": [
                    "ips"
                  ]
                }
              }
            }
          }
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "digitalAudioProcessor": {
          "type": "object",
          "properties": {
            "serialNumber": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "string"
                }
              ]
            },
            "manufacturer": {
              "type": "string"
            },
            "model": {
              "type": "string",
              "enum":[
                "PCM-1610",
                "PCM-1630",
                "PCM-F1",
                "DAS-900"
              ]
            }
          }
        },
        "takeNumber": {
          "$ref": "fields#takeNumber"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/versions/1.1/sample/sample_digitized_audiocassettedigital.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.wav",
		"fileRole": "pm",
		"schemaVersion": "1.0.0"
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myd",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Dance Audio 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "abc123",
		"extension": "wav",
		"dateCreated": "2016-01-01",
		"fileFormat": "BWF",
		"audioCodec": "PCM",
		"fileSize": {
			"measure": 2000000000,
			"unit": "B"
		},
		"durationMilli": {
			"measure": 3600000,
			"unit": "ms"
		},
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio cassette digital",
			"format": "DAT",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 1,
			"streamNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"stockLength": {
				"measure": 60,
				"unit": "min"
			},
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": {
				"measure": 0.125,
				"unit": "in"
			},
			"tapeThickness": {
				"measure": 1.5,
				"unit": "mils"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "ferrichrome"
		},
		"audioRecording": {
			"audioSoundField": "quadrophonic",
			"numberOfAudioTracks": 4,
			"trackConfiguration": "full-track",
			"designatedSpeed": {
				"measure": 0.3209,
				"unit": "ips"
			},
			"audioBitDepth": {
				"measure": 24,
				"unit": "bit"
			},
			"audioSamplingRate": {
				"measure": 22500,
				"unit": "hz"
			}
		},
		"notes": {
			"physicalConditionPreShipNotes": "cassette shows XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"speed": {
				"measure": 0.3209,
				"unit": "ips"
			}
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
