=== NYPL/ami-metadata/versions/0.7/schema/digitized_audioreel.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Digitized Audio Reel Schema",
  "id": "digitized_audioreel",
  "description": "Definitions for audio reel fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "id": "technical",
      "type": "object",
      "additionalProperties": false,
      "require": [
        "filename",
        "extension",
        "dateCreated",
        "fileFormat",
        "audioCodec",
        "fileSize",
        "durationMilli",
        "durationHuman"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
          "enum": [
             "WAV", "wav"
           ]
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "enum": [ "BWF" ]
        },
        "audioCodec": {
          "enum": [
            "PCM", "pcm"
          ]
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        },
        "signalNotes": {
          "$ref": "fields#technicalSignalNotes"
        }
      }
    },
    "source": {
      "id": "source",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "object",
        "subObject",
        "physicalDescription",
        "audioRecording"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "audio reel" ]
            },
            "format": {
              "enum": [
                "half-inch open-reel audio",
                "one-inch open-reel audio",
                "quarter-inch open-reel audio",
                "two-inch open-reel audio",
                "unknown"
              ]
            },
            "generation": {
              "type": "string"
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "subObject": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "faceNumber"
          ],
          "properties": {
            "faceNumber": {
              "type": "number",
              "multipleOf": 1.0
            },
            "regionNumber": {
              "type": "number",
              "multipleOf": 1.0
            },
            "streamNumber": {
              "type": "number",
              "multipleOf": 1.0
            },
            "partNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "diameter",
            "stockManufacturer",
            "stockProductID",
            "tapeWidth",
            "tapeThickness",
            "baseMaterial",
            "oxideMaterial"
          ],
          "properties": {
            "diameter": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.25
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "stockProductID": {
              "type": "string"
            },
            "stockManufacturer": {
              "type": "string"
            },
            "tapeWidth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    0.25,
                    0.5,
                    1,
                    2
                  ]
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "tapeThickness": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    0.5,
                    1,
                    1.5
                  ]
                },
                "unit": {
                  "enum": [
                    "mils"
                  ]
                }
              }
            },
            "baseMaterial": {
              "enum": [
                "acetate",
                "polyester",
                "PVC",
                "paper",
                "unknown"
              ]
            },
            "oxideMaterial": {
              "enum": [
                "ferric oxide",
                "chromium dioxide",
                "unknown"
              ]
            },
            "backcoatMaterial": {
              "enum": [
                "yes",
                "no"
              ]
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "audioSoundField",
            "numberOfAudioTracks",
            "trackConfiguration",
            "designatedSpeed",
            "designatedNoiseReduction",
            "designatedEQ"
          ],
          "properties": {
            "audioSoundField": {
              "enum": [
                "stereo",
                "mono",
                "surround",
                "quadrophonic",
                "binaural",
                "unknown"
              ]
            },
            "numberOfAudioTracks": {
              "enum": [
                1,
                2,
                3,
                4,
                8,
                16,
                24,
                "n/a"
              ]
            },
            "trackConfiguration": {
              "enum": [
                "full-track",
                "half-track",
                "quarter-track",
                "2 track",
                "3 track",
                "4 track",
                "8 track",
                "16 track",
                "24 track",
                "unknown"
              ]
            },
            "designatedSpeed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    30,
                    15,
                    7.5,
                    3.75,
                    1.875,
                    0.9375,
                    "unknown"
                  ]
                },
                "unit": {
                  "enum": [
                    "ips"
                  ]
                }
              }
            },
            "designatedNoiseReduction": {
              "enum": [
                "Dolby A",
                "Dolby B",
                "Dolby SR",
                "DBX I",
                "DBX II",
                "Tel Com/High Com",
                "unknown"
              ]
            },
            "designatedEQ": {
              "enum": [
                "NAB",
                "IEC/CCIR",
                "unknown"
              ]
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model",
            "tapeHeadType",
            "eq",
            "speed"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#playbackDeviceID"
            },
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            },
            "tapeHeadType": {
              "enum": [
                "full-track",
                "half-track",
                "quarter-track",
                "2 track",
                "3 track",
                "4 track",
                "8 track",
                "16 track",
                "24 track"
              ]
            },
            "operatingLevel": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    185,
                    200,
                    224,
                    250,
                    280,
                    315,
                    320,
                    355,
                    400,
                    450,
                    500
                  ]
                },
                "unit": {
                  "enum": [
                    "nW/m"
                  ]
                }
              }
            },
            "noiseReduction": {
              "enum": [
                "Dolby A",
                "Dolby B",
                "Dolby SR",
                "DBX I",
                "DBX II",
                "Tel Com/High Com",
                "n/a"
              ]
            },
            "eq": {
              "enum": [
                "NAB",
                "IEC"
              ]
            },
            "speed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    30,
                    15,
                    7.5,
                    3.75,
                    1.875,
                    0.9375,
                    3.12,
                    6.25
                  ]
                },
                "unit": {
                  "enum": [
                    "ips"
                  ]
                }
              }
            }
          }
        },
        "analogDigitalConverter": {
          "$ref": "fields#analogDigitalConverter"
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "takeNumber": {
          "$ref": "fields#takeNumber"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/versions/1.1/sample/sample_digitized_audioreel.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.wav",
		"fileRole": "pm",
		"schemaVersion": "1.1.0"
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myh",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Dance Audio 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "myh_abc123_v01_pm",
		"extension": "wav",
		"dateCreated": "2016-01-01",
		"fileFormat": "BWF",
		"audioCodec": "PCM",
		"fileSize": {
			"measure": 2000000000,
			"unit": "B"
		},
		"durationMilli": {
			"measure": 3600000,
			"unit": "ms"
		},
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio reel",
			"format": "quarter-inch open-reel audio",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 2,
			"streamNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"diameter": {
				"measure": 7,
				"unit": "in"
			},
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": {
				"measure": 0.25,
				"unit": "in"
			},
			"tapeThickness": {
				"measure": 1.5,
				"unit": "mils"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "chromium dioxide",
			"backcoatMaterial": "yes"
		},
		"audioRecording": {
			"audioSoundField": "quadrophonic",
			"numberOfAudioTracks": 24,
			"trackConfiguration": "full-track",
			"designatedSpeed": {
				"measure": 7.5,
				"unit": "ips"
			},
			"designatedNoiseReduction": "DBX II",
			"designatedEQ": "NAB"
		},
		"notes": {
			"physicalConditionPreShipNotes": "reel show XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows XYZ damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"tapeHeadType": "full-track",
			"operatingLevel": {
				"measure": 315,
				"unit": "nW/m"
			},
			"noiseReduction": "DBX II",
			"eq": "NAB",
			"speed": {
				"measure": 7.5,
				"unit": "ips"
			}
		},
		"analogDigitalConverter": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer D",
			"model": "Model XYZ",
			"operatingLevel": {
				"measure": -20,
				"unit": "dBFS"
			}
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
