=== NYPL/ami-metadata/schema/digitized_audiogrooveddisc.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Digitized Audio Grooved Disc Schema",
  "id": "digitized_audiogrooveddisc",
  "description": "Definitions for audio grooved disc fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": {
      "id": "technical",
      "type": "object",
      "additionalProperties": false,
      "require": [
        "filename",
        "extension",
        "dateCreated",
        "fileFormat",
        "audioCodec",
        "fileSize",
        "durationMilli",
        "durationHuman"
      ],
      "properties": {
        "filename": {
          "$ref": "fields#technicalFilename"
        },
        "extension": {
          "enum": [ "WAV" ]
        },
        "dateCreated": {
          "$ref": "fields#technicalDateCreated"
        },
        "fileFormat": {
          "enum": [ "BWF" ]
        },
        "audioCodec": {
          "enum": [ "PCM" ]
        },
        "fileSize": {
          "$ref": "fields#technicalFileSize"
        },
        "durationMilli": {
          "$ref": "fields#technicalDurationMilli"
        },
        "durationHuman": {
          "$ref": "fields#technicalDurationHuman"
        },
        "signalNotes": {
          "$ref": "fields#technicalSignalNotes"
        }
      }
    },
    "source": {
      "id": "source",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "object",
        "subObject",
        "physicalDescription",
        "audioRecording"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "audio grooved disc" ]
            },
            "format": {
              "enum": [
                "disc, Edison Diamond Disc",
                "disc, Edison Voicewriter",
                "disc, flexible",
                "disc, gelatin",
                "disc, lacquer, glass base",
                "disc, lacquer, metal base",
                "disc, lacquer, paper base",
                "disc, metal",
                "disc, metal master",
                "disc, other",
                "disc, shellac",
                "disc, vinyl"
              ]
            },
            "generation": {
              "enum": [
                "unknown",
                "Archive Original",
                "Preservation Master",
                "Copy"
              ]
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "subObject": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "faceNumber"
          ],
          "properties": {
            "faceNumber": {
              "type": "number",
              "multipleOf": 1.0
            },
            "regionNumber": {
              "type": "number",
              "multipleOf": 1.0
            },
            "partNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "physicalDescription": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "stockManufacturer",
            "stockProductID",
            "diameter",
            "surfaceMaterial",
            "baseMaterial",
            "grooveWidth",
            "grooveOrientation"
          ],
          "properties": {
            "stockManufacturer": {
              "type": "string"
            },
            "stockProductID": {
              "type": "string"
            },
            "diameter": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    5.5,
                    7,
                    10,
                    10.75,
                    12,
                    16,
                    17.5,
                    20
                  ]
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "baseMaterial": {
              "enum": [
                "shellac",
                "vinyl",
                "aluminum",
                "glass",
                "paper",
                "nickel-plated copper",
                "zinc",
                "unknown metal",
                "unknown"
              ]
            },
            "surfaceMaterial": {
              "enum": [
                "cellulose acetate",
                "cellulose nitrate",
                "celluloid",
                "gelatin",
                "none",
                "unknown"
              ]
            },
            "grooveOrientation": {
              "enum": [
                "lateral",
                "vertical"
              ]
            },
            "grooveWidth": {
              "enum": [
                "coarse",
                "microgroove"
              ]
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "audioSoundField",
            "designatedSpeed"
          ],
          "properties": {
            "audioSoundField": {
              "enum": [
                "stereo",
                "mono",
                "quadrophonic",
                "binaural",
                "unknown"
              ]
            },
            "designatedSpeed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    33,
                    45,
                    70,
                    71.29,
                    76.59,
                    78.26,
                    80,
                    "unknown"
                  ]
                },
                "unit": {
                  "enum": [
                    "rpm"
                  ]
                }
              }
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "analogDigitalConverter",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model",
            "speed",
            "trackingWeight",
            "groovedWallPlayback",
            "phonoArm",
            "phonoCartridge",
            "phonoPreamp"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#playbackDeviceID"
            },
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            },
            "speed": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "enum": [
                    33,
                    45,
                    70,
                    71.29,
                    76.59,
                    78.26,
                    80
                  ]
                },
                "unit": {
                  "enum": [
                    "rpm"
                  ]
                }
              }
            },
            "trackingWeight": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number"
                },
                "unit": {
                  "enum": [
                    "g"
                  ]
                }
              }
            },
            "groovedWallPlayback": {
              "enum": [
                "left only",
                "right only",
                "left + right",
                "left - right",
                "left and right discrete"
              ]
            },
            "phonoArm": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "serialNumber",
                "manufacturer",
                "model"
              ],
              "properties": {
                "serialNumber": {
                  "type": "string"
                },
                "manufacturer": {
                  "type": "string"
                },
                "model": {
                  "type": "string"
                }
              }
            },
            "phonoCartridge": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "manufacturer",
                "model",
                "stylusShape",
                "stylusSize"
              ],
              "properties": {
                "manufacturer": {
                  "type": "string"
                },
                "model": {
                  "type": "string"
                },
                "stylusShape": {
                  "enum": [
                    "elliptical",
                    "truncated elliptical",
                    "conical",
                    "truncated conical",
                    "Edison C",
                    "spherical"
                  ]
                },
                "stylusSize": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "measure",
                    "unit"
                  ],
                  "properties": {
                    "measure": {
                      "type": "number"
                    },
                    "unit": {
                      "enum": [
                        "mils"
                      ]
                    }
                  }
                }
              }
            },
            "phonoPreamp":{
              "serialNumber": {
                "type": "string"
              },
              "manufacturer": {
                "type": "string"
              },
              "model": {
                "type": "string"
              },
              "eq": {
                "enum": [
                  "NAB LP",
                  "RIAA",
                  "AES LP",
                  "CCIR LP",
                  "FFRR LP",
                  "NAB 78",
                  "Decca",
                  "FFRR 78",
                  "HMV"
                ]
              },
              "eqRolloff": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "measure",
                  "unit"
                ],
                "properties": {
                  "measure": {
                    "enum": [
                      0,
                      -5,
                      -6,
                      -7,
                      -8.5,
                      -10,
                      -12,
                      -14,
                      -16,
                      -18
                    ]
                  },
                  "unit": {
                    "enum": [
                      "dB"
                    ]
                  }
                }
              },
              "eqTurnover": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "measure",
                  "unit"
                ],
                "properties": {
                  "measure": {
                    "enum": [
                      0,
                      150,
                      200,
                      250,
                      300,
                      375,
                      400,
                      500,
                      629,
                      750,
                      1000
                    ]
                  },
                  "unit": {
                    "enum": [
                      "Hz"
                    ]
                  }
                }
              }
            }
          }
        },
        "analogDigitalConverter": {
          "$ref": "fields#analogDigitalConverter"
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "takeNumber": {
          "$ref": "fields#takeNumber"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/sample/sample_digitized_audiogrooveddisc.json
{
	"asset": {
		"referenceFilename": "myh_abc123_v01_pm.wav",
		"fileRole": "pm",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": "123456",
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": "12345",
		"barcode": "33433123456789",
		"divisionCode": "myh",
		"vernacularDivisionCode": "DAN",
		"projectCode": "projectXYZ",
		"title": "Dance Audio 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "myh_abc123_v01_pm",
		"extension": "WAV",
		"dateCreated": "2016-01-01",
		"fileFormat": "BWF",
		"audioCodec": "PCM",
		"fileSize": {
			"measure": 2000000000,
			"unit": "B"
		},
		"durationMilli": {
			"measure": 3600000,
			"unit": "ms"
		},
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio grooved disc",
			"format": "disc, Edison Diamond Disc",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 2,
			"partNumber": 1
		},
		"physicalDescription": {
			"diameter": {
				"measure": 7,
				"unit": "in"
			},
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "xyz123",
			"baseMaterial": "nickel-plated copper",
			"surfaceMaterial": "celluloid",
			"grooveOrientation": "lateral",
			"grooveWidth": "coarse"
		},
		"audioRecording": {
			"audioSoundField": "mono",
			"designatedSpeed": {
				"measure": 45,
				"unit": "rpm"
			}
		},
		"notes": {
			"physicalConditionPreShipNotes": "disc shows XYZ damage",
			"physicalConditionDigitizationNotes": "disc shows XYZ damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"speed": {
				"measure": 45,
				"unit": "rpm"
			},
			"phonoArm": {
				"serialNumber": "xyz123",
				"manufacturer": "Manufacturer I",
				"model": "Model XYZ"
			},
			"phonoCartridge": {
				"manufacturer": "Manufacturer G",
				"model": "Model XYZ",
				"stylusShape": "elliptical",
				"stylusSize": {
					"measure": 12,
					"unit": "mils"
				}
			},
			"trackingWeight": {
				"measure": 0.5,
				"unit": "g"
			},
			"groovedWallPlayback": "left + right",
			"phonoPreamp": {
				"serialNumber": "xyz123",
				"manufacturer": "Manufacturer H",
				"model": "Model XYZ",
				"eq": "RIAA LP",
				"eqRolloff": {
					"measure": -6,
					"unit": "dB"
				},
				"eqTurnover": {
					"measure": 250,
					"unit": "Hz"
				}
			}
		},
		"analogDigitalConverter": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer D",
			"model": "Model XYZ",
			"operatingLevel": {
				"measure": -20,
				"unit": "dBFS"
			}
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}
