=== NYPL/ami-metadata/schema/digitized_videocassette.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Digitized Video Cassette Schema",
  "id": "digitized_videocassette",
  "description": "Definitions for audio optical fields",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "asset",
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": { "$ref": "fields#asset" },
    "bibliographic": { "$ref": "fields#bibliographic" },
    "technical": { "$ref": "fields#technical" },
    "source": {
      "id": "source",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "object",
        "subObject",
        "stock",
        "contentSpecifications",
        "audioRecording"
      ],
      "properties": {
        "object": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "format",
            "volumeNumber"
          ],
          "properties": {
            "type": {
              "enum": [ "video cassette" ]
            },
            "format": {
              "enum": [
                "3/4 inch U-matic",
                "Betacam",
                "Betacam SP",
                "Betacam SX",
                "Betamax",
                "D-1",
                "D-2",
                "D-3",
                "Digital8",
                "Digital Betacam",
                "DVCam",
                "DVCPRO",
                "DVCPRO HD",
                "HDCAM",
                "HDV",
                "Hi8",
                "MII",
                "MiniDV",
                "SVHS",
                "VHS",
                "Video8"
              ]
            },
            "volumeNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "subObject": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "faceNumber": {
              "type": "number",
              "multipleOf": 1.0
            },
            "regionNumber": {
              "type": "number",
              "multipleOf": 1.0
            },
            "partNumber": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "stock": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "stockManufacturer",
            "stockProductID",
            "tapeWidth",
            "baseMaterial",
            "oxideMaterial"
          ],
          "properties": {
            "stockLength": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 1.0
                },
                "unit": {
                  "enum": [
                    "min"
                  ]
                }
              }
            },
            "stockManufacturer": {
              "type": "string"
            },
            "stockProductID": {
              "type": "string"
            },
            "tapeWidth": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "measure",
                "unit"
              ],
              "properties": {
                "measure": {
                  "type": "number",
                  "multipleOf": 0.01
                },
                "unit": {
                  "enum": [
                    "in"
                  ]
                }
              }
            },
            "baseMaterial": {
              "enum": [
                "acetate",
                "polyester",
                "PVC",
                "paper"
              ]
            },
            "oxideMaterial": {
              "enum": [
                "ferric oxide",
                "chromium dioxide",
                "unknown"
              ]
            }
          }
        },
        "contentSpecifications": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "broadcastStandard",
            "colorBW"
          ],
          "properties": {
            "broadcastStandard": {
              "enum": [
                "NTSC",
                "PAL",
                "SECAM"
              ]
            },
            "colorBW": {
              "enum": [
                "b/w",
                "color",
                "color & b/w"
              ]
            }
          }
        },
        "audioRecording": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "audioSoundField",
            "numberOfAudioTracks"
          ],
          "properties": {
            "audioSoundField": {
              "enum": [
                "stereo",
                "mono",
                "surround"
              ]
            },
            "numberOfAudioTracks": {
              "type": "number",
              "multipleOf": 1.0
            }
          }
        },
        "notes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "physicalConditionPreShipNotes": {
              "type": "string"
            },
            "physicalConditionDigitizationNotes": {
              "type": "string"
            }
          }
        }
      }
    },
    "digitizationProcess" : {
      "id": "digitizationProcess",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "playbackDevice",
        "timeBaseCorrector",
        "captureSoftware"
      ],
      "properties": {
        "playbackDevice": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#playbackDeviceID"
            },
            "serialNumber": {
              "$ref": "fields#playbackDeviceSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#playbackDeviceManufacturer"
            },
            "model": {
              "$ref": "fields#playbackDeviceModel"
            }
          }
        },
        "analogDigitalConverter": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#analogDigitalConverterID"
            },
            "serialNumber": {
              "$ref": "fields#analogDigitalConverterSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#analogDigitalConverterManufacturer"
            },
            "model": {
              "$ref": "fields#analogDigitalConverterModel"
            }
          }
        },
        "timeBaseCorrector": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#timeBaseCorrectorID"
            },
            "serialNumber": {
              "$ref": "fields#timeBaseCorrectorSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#timeBaseCorrectorManufacturer"
            },
            "model": {
              "$ref": "fields#timeBaseCorrectorModel"
            }
          }
        },
        "analogDigitalConverter": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "serialNumber",
            "manufacturer",
            "model"
          ],
          "properties": {
            "id":  {
              "$ref": "fields#analogDigitalConverterID"
            },
            "serialNumber": {
              "$ref": "fields#analogDigitalConverterSerialNumber"
            },
            "manufacturer": {
              "$ref": "fields#analogDigitalConverterManufacturer"
            },
            "model": {
              "$ref": "fields#analogDigitalConverterModel"
            }
          }
        },
        "captureSoftware": {
          "$ref": "fields#captureSoftware"
        },
        "take": {
          "$ref": "fields#take"
        },
        "notes": {
          "$ref": "fields#processNotes"
        }
      }
    },
    "digitizer": { "$ref": "fields#digitizer" }
  }
}

=== NYPL/ami-metadata/sample/sample_vendor_videocassette.json
{
	"asset": {
		"referenceFilename": "abc.mov",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"mmsCollectionID": "12345678-1234-1234-1234-123456789abc",
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Dance Video 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Video 2 instead of Dance Video 1"
	},
	"technical": {
		"filename": "abc123.mov",
		"extension": "mov",
		"dateCreated": "2016-01-01",
		"fileFormat": "MOV file",
		"fileCodec": "4cc",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "11:54:54",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "video cassette",
			"format": "3/4 inch U-matic",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 2,
			"regionNumber": 2,
			"partNumber": 1
		},
		"stock": {
			"stockLength": {
				"measure": 60,
				"unit": "min"
			},
			"stockManufacturer": "Sony",
			"stockProductID": "KCA-60",
			"tapeWidth": {
				"measure": 1.1,
				"unit": "in"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "ferric oxide"
		},
		"contentSpecifications": {
			"broadcastStandard": "SECAM",
			"colorBW": "b/w"
		},
		"audioRecording": {
			"audioSoundField": "surround",
			"numberOfAudioTracks": 1
		},
		"notes": {
			"physicalConditionPreShipNotes": "reel show XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows XYZ damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ"
		},
		"timeBaseCorrector": {
			"id": "id12345",
			"serialNumber": 12345,
      "manufacturer": "Manufacturer C",
      "model": "Model XYZ"
		},
		"analogDigitalConverter" : {
      "id": "id12345",
      "serialNumber": "id12345abc",
      "manufacturer": "Manufacturere D",
      "model": "Model XYZ"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required two takes for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
			"addressStreet1": "123 ABC St",
			"addressStreet2": "Suite 1234",
			"addressCity": "Anytown",
			"addressState": "ST",
			"addressZip": 12345
		}
	}
}
