=== NYPL/ami-metadata/schema/vendor_all_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "vendor_all_schema",
  "title": "AMI Vendor Schema",
  "description": "Base validation schema for metadata sent with media to digitization",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "bibliographic",
    "technical",
    "source",
    "digitizationProcess",
    "digitizer"
  ],
  "properties": {
    "asset": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "referenceFilename" : {
          "type": "string",
          "pattern": "^.+\\.[a-zA-Z0-9]{3}"
        },
        "schemaVersion": {
          "type": "number",
          "multipleOf": 1.0
        }
      }
    },
    "bibliographic": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "primaryID": {
          "type": "string"
        },
        "classmark": {
          "type": "string"
        },
        "danceFormerClassmark": {
          "type": "string"
        },
        "nonCMSItemID": {
          "type": "string"
        },
        "cmsItemID": {
          "type": "number",
          "minimum": 100000,
          "maximum": 999999
        },
        "cmsCollectionID": {
          "type": "string"
        },
        "catalogBNumber": {
          "type": "string",
          "pattern": "^(b|B)[0-9]{8}$"
        },
        "mssID": {
          "type": "number",
          "minimum": 10000,
          "maximum": 99999
        },
        "barcode": {
          "type": "number",
          "minimum": 33433000000000,
          "maximum": 33433999999999
        },
        "mmsCollectionID": {
          "type": "string",
          "pattern": "^[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$"
        },
        "divisionCode": {
          "type": "string",
          "pattern": "^[a-zA-Z]{3}$"
        },
        "vernacularDivisionCode": {
          "type": "string"
        },
        "projectCode": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "date": {
          "type": "string"
        },
        "contentNotes": {
          "type": "string"
        }
      }
    },
    "technical": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "filename": {
          "type": "string",
          "pattern": "^.+\\.[a-zA-Z0-9]{3}"
        },
        "extensionv": {
          "type": "string",
          "pattern": "[a-zA-Z0-9]{3}"
        },
        "dateCreated": {
          "type": "string",
          "pattern": "201[6-9]-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])"
        },
        "fileFormat": {
          "type": "string"
        },
        "fileCodec": {
          "type": "string"
        },
        "fileSize": {
          "type": "number",
          "multipleOf": 1.0
        },
        "durationMilli": {
          "type": "number"
        },
        "durationHuman": {
          "type": "string",
          "pattern": "[0-9]{2}:[0-5][0-9]:[0-5][0-9]"
        },
        "signalNotes": {
          "type": "string"
        }
      }
    },
    "source": {
      "type": "object",
      "id": "#source",
      "oneOf": [
        { "$ref": "vendor_audiooptical#source" },
        { "$ref": "vendor_audioreel#source" },
        { "$ref": "vendor_videooptical#source" },
        { "$ref": "vendor_videocassette#source" },
        { "$ref": "vendor_videoreel#source" }
      ]
    },
    "digitizationProcess": {
      "type": "object",
      "id": "#digitizationProcess",
      "anyOf": [
        { "$ref": "vendor_audiooptical#digitizationProcess" },
        { "$ref": "vendor_audioreel#digitizationProcess" },
        { "$ref": "vendor_videooptical#digitizationProcess" },
        { "$ref": "vendor_videocassette#digitizationProcess" },
        { "$ref": "vendor_videoreel#digitizationProcess" }
      ]
    },
    "digitizer": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "operator": {
          "type": "object",
          "properties": {
            "operatorLastName": {
              "type": "string"
            },
            "operatorLastName": {
              "type": "string"
            }
          }
        },
        "organization": {
          "type": "object",
          "properties": {
            "organizationName": {
              "type": "string"
            },
            "organizationAddressStreet1": {
              "type": "string"
            },
            "organizationAddressStreet2": {
              "type": "string"
            },
            "organizationAddressCity": {
              "type": "string"
            },
            "organizationAddressState": {
              "type": "string",
              "pattern": "^[A-Z]{2}$"
            },
            "organizationAddressZip": {
              "type": "number",
              "minimum": 10000,
              "maximum": 99999
            }
          }
        }
      }
    }
  }
}

=== NYPL/ami-metadata/sample/sample_digitized_audiodigitalcassette.json
{
	"asset": {
		"referenceFilename": "abc",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Dance Audio 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "abc123",
		"extension": "wav",
		"dateCreated": "2016-01-01",
		"fileFormat": "WAV file",
		"fileCodec": "PCM",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio digital cassette",
			"format": "Digital Compact Cassette",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 1,
			"streamNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"stockLength": {
				"measure": 60,
				"unit": "min"
			},
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": {
				"measure": 0.125,
				"unit": "in"
			},
			"tapeThickness": {
				"measure": 1.5,
				"unit": "mils"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "ferrichrome",
			"backcoatMaterial": "yes"
		},
		"audioRecording": {
			"audioSoundField": "quadrophonic",
			"numberOfAudioTracks": 4,
			"trackConfiguration": "full-track",
			"designatedSpeed": ".3209 (Standard)",
			"audioBitDepth": {
				"measure": 24,
				"unit": "bit"
			},
			"audioSamplingRate": {
				"measure": 22500,
				"unit": "hz"
			}
		},
		"notes": {
			"physicalConditionPreShipNotes": "cassette shows XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"speed": ".3209 (Standard)"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
      "address": {
        "street1": "123 ABC St",
        "street2": "Suite 1234",
        "city":    "Anytown",
        "state":   "ST",
        "postalCode": "12345"
      }
		}
	}
}

=== NYPL/ami-metadata/sample/sample_vendor_audiodigitalcassette.json
{
	"asset": {
		"referenceFilename": "abc.mov",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"mmsCollectionID": "12345678-1234-1234-1234-123456789abc",
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Dance Video 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Video 2 instead of Dance Video 1"
	},
	"technical": {
		"filename": "abc123.mov",
		"extensionv": "mov",
		"dateCreated": "2016-01-01",
		"fileFormat": "MOV file",
		"fileCodec": "4cc",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "11:54:54",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio digital cassette",
			"format": "Digital Compact Cassette",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 2,
			"regionNumber": 2,
			"streamNumber": 1,
			"partNumber": 1
		},
		"stock": {
			"stockLength": 60,
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": 0.25,
			"tapeThickness": 240,
			"baseMaterial": "acetate",
			"oxideMaterial": "ferrichrome",
			"backcoatMaterial": "yes"
		},
		"audioRecording": {
			"audioSoundField": "quadrophonic",
			"numberOfAudioTracks": 4,
			"trackConfiguration": "full-track",
			"designatedSpeed": ".3209 (Standard)",
			"audioBitDepth": 18,
			"audioSamplingRate": 22500
		},
		"notes": {
			"physicalConditionPreShipNotes": "reel show XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows XYZ damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"playbackDeviceSerialNumber": "xyz123",
			"playbackDeviceManufacturer": "Manufacturer B",
			"playbackDeviceModel": "Model XYZ",
			"playbackSpeed": ".3209 (Standard)"
		},
		"captureSoftware": {
			"captureSoftwareManufacturer": "Manufacturer E",
			"captureSoftwareProductName": "Product XYZ",
			"captureSoftwareVersion": "Version 123",
			"captureSoftwarePlatform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required two takes for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"operatorLastName": "Doe",
			"operatorLastName": "Jane"
		},
		"organization": {
			"organizationName": "Organization XYZ",
			"organizationAddressStreet1": "123 ABC St",
			"organizationAddressStreet2": "Suite 1234",
			"organizationAddressCity": "Anytown",
			"organizationAddressState": "ST",
			"organzationAddressZip": 12345
		}
	}
}

=== NYPL/ami-metadata/sample/sample_digitized_audioanalogcassette.json
{
	"asset": {
		"referenceFilename": "abc",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"mmsCollectionID": "12345678-1234-1234-1234-123456789abc",
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Audio Cassette 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "abc123",
		"extension": "wav",
		"dateCreated": "2016-01-01",
		"fileFormat": "WAV file",
		"fileCodec": "PCM",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio analog cassette",
			"format": "cassette",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 2,
			"regionNumber": 1,
			"streamNumber": 1,
			"partNumber": 1
		},
		"stock": {
			"stockLength": {
				"measure": 60,
				"unit": "min"
			},
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": {
				"measure": 0.25,
				"unit": "in"
			},
			"tapeThickness": {
				"measure": 240,
				"unit": "mils"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "ferrichrome",
			"backcoatMaterial": "yes"
		},
		"audioRecording": {
			"audioSoundField": "quadrophonic",
			"numberOfAudioTracks": 4,
			"trackConfiguration": "full-track",
			"designatedSpeed": {
				"measure": 0.9375,
				"unit": "ips"
			},
			"designatedNoiseReduction": "Dolby B",
			"designatedEQ": "Type II"
		},
		"notes": {
			"physicalConditionPreShipNotes": "cassette XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"tapeHeadType": "full-track",
			"noiseReduction": "Dolby B",
			"eq": "Type II",
			"speed": {
				"measure": 0.9375,
				"unit": "ips"
			}
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
			"addressStreet1": "123 ABC St",
			"addressStreet2": "Suite 1234",
			"addressCity": "Anytown",
			"addressState": "ST",
			"addressPostalCode": 12345
		}
	}
}

=== NYPL/ami-metadata/sample/sample_digitized_audiooptical.json
{
	"asset": {
		"referenceFilename": "abc",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Dance Audio 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Audio 2 instead of Dance Audio 1"
	},
	"technical": {
		"filename": "abc123",
		"extension": "wav",
		"dateCreated": "2016-01-01",
		"fileFormat": "WAV file",
		"fileCodec": "PCM",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio optical disc",
			"format": "CD-R",
			"generation": 2,
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 1,
			"streamNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"stockManufacturer": "Manufacturer A",
			"discDiameter": {
				"measure": 4.7,
				"unit": "in"
			},
			"dyeLayer": "phthalocyanine",
			"reflectiveLayer": "silver"
		},
		"audioRecording": {
			"audioSoundField": "stereo"
		},
		"notes": {
			"physicalConditionPreShipNotes": "disc shows XYZ damage",
			"physicalConditionDigitizationNotes": "medium shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
			"addressStreet1": "123 ABC St",
			"addressStreet2": "Suite 1234",
			"addressCity": "Anytown",
			"addressState": "ST",
			"addressPostalCode": 12345
		}
	}
}

=== NYPL/ami-metadata/sample/sample_vendor_audioanalogcassette.json
{
	"asset": {
		"referenceFilename": "abc.mov",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"mmsCollectionID": "12345678-1234-1234-1234-123456789abc",
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Dance Video 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Video 2 instead of Dance Video 1"
	},
	"technical": {
		"filename": "abc123.mov",
		"extension": "mov",
		"dateCreated": "2016-01-01",
		"fileFormat": "MOV file",
		"fileCodec": "4cc",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "11:54:54",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio analog cassette",
			"format": "microcassette",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 2,
			"regionNumber": 2,
			"streamNumber": 1,
			"partNumber": 1
		},
		"stock": {
			"stockLength": 60,
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": 0.25,
			"tapeThickness": 240,
			"baseMaterial": "acetate",
			"oxideMaterial": "ferrichrome",
			"backcoatMaterial": "yes"
		},
		"audioRecording": {
			"audioSoundField": "quadrophonic",
			"numberOfAudioTracks": 4,
			"trackConfiguration": "full-track",
			"designatedSpeed": 1.875,
			"designatedNoiseReduction": "Dolby B",
			"designatedEQ": "Type II"
		},
		"notes": {
			"physicalConditionPreShipNotes": "reel show XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows XYZ damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"tapeHeadType": "full-track",
			"noiseReduction": "Dolby B",
			"eq": "Type II",
			"speed": 1.875
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required two takes for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
			"addressStreet1": "123 ABC St",
			"addressStreet2": "Suite 1234",
			"addressCity": "Anytown",
			"addressState": "ST",
			"addressZip": 12345
		}
	}
}

=== NYPL/ami-metadata/sample/sample_vendor_audioreel.json
{
	"asset": {
		"referenceFilename": "abc",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"mmsCollectionID": "12345678-1234-1234-1234-123456789abc",
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Dance Video 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Video 2 instead of Dance Video 1"
	},
	"technical": {
		"filename": "abc123",
		"extension": "mov",
		"dateCreated": "2016-01-01",
		"fileFormat": "MOV file",
		"fileCodec": "4cc",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "11:54:54.999",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "audio reel",
			"format": "1/4 inch open reel audio",
			"generation": "unknown",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 2,
			"regionNumber": 2,
			"streamNumber": 1,
			"partNumber": 1
		},
		"stock": {
			"reelDiameter": {
				"measure": 7,
				"unit": "in"
			},
			"stockManufacturer": "Manufacturer A",
			"stockProductID": "idabc123",
			"tapeWidth": {
				"measure": 0.25,
				"unit": "in"
			},
			"tapeThickness": {
				"measure": 240,
				"unit": "mils"
			},
			"baseMaterial": "acetate",
			"oxideMaterial": "chromium dioxide",
			"backcoatMaterial": "yes"
		},
		"audioRecording": {
			"audioSoundField": "quadrophonic",
			"numberOfAudioTracks": 24,
			"trackConfiguration": "full-track",
			"designatedSpeed": {
				"measure": 7.5,
				"unit": "ips"
			},
			"designatedNoiseReduction": "DBX II",
			"designatedEQ": "NAB"
		},
		"notes": {
			"physicalConditionPreShipNotes": "reel show XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows XYZ damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ",
			"tapeHeadType": "full-track",
			"operatingLevel": {
				"measure": 315,
				"unit": "nW/m"
			},
			"noiseReduction": "DBX II",
			"eq": "NAB",
			"speed": {
				"measure": 7.5,
				"unit": "ips"
			}
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required two takes for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
			"addressStreet1": "123 ABC St",
			"addressStreet2": "Suite 1234",
			"addressCity": "Anytown",
			"addressState": "ST",
			"addressZip": 12345
		}
	}
}

=== NYPL/ami-metadata/sample/sample_digitized_videocassette.json
{
	"asset": {
		"referenceFilename": "abc",
		"schemaVersion": 1
	},
	"bibliographic": {
		"primaryID": "abc123",
		"classmark": "*ABC 123",
		"formerClassmark": "*NCOW 123",
		"nonCMSID": "string123",
		"cmsItemID": 123456,
		"cmsCollectionID": "string123",
		"catalogBNumber": "B12345678",
		"mssID": 12345,
		"barcode": 33433123456789,
		"divisionCode": "MYH",
		"vernacularDivisionCode": "Dance",
		"projectCode": "projectXYZ",
		"title": "Dance Video 1",
		"date": "Late 1970s",
		"contentNotes": "media is actually Dance Video 2 instead of Dance Video 1"
	},
	"technical": {
		"filename": "abc123",
		"extension": "mov",
		"dateCreated": "2016-01-01",
		"fileFormat": "MOV file",
		"fileCodec": "v210",
		"fileSize": 123456789012,
		"durationMilli": 3600000,
		"durationHuman": "1:00:00.000",
		"signalNotes": "signal undreadable at point 123"
	},
	"source": {
		"object": {
			"type": "video cassette",
			"format": "3/4 inch U-matic",
			"volumeNumber": 1
		},
		"subObject": {
			"faceNumber": 1,
			"regionNumber": 1,
			"partNumber": 1
		},
		"physicalDescription": {
			"stockLength": {
				"measure": 60,
				"unit": "min"
			},
			"stockManufacturer": "Sony",
			"stockProductID": "KCA-60",
			"tapeWidth": {
				"measure": 0.75,
				"unit": "in"
			},
			"baseMaterial": "polyester",
			"oxideMaterial": "ferric oxide"
		},
		"contentSpecifications": {
			"broadcastStandard": "SECAM",
			"colorBW": "b/w"
		},
		"audioRecording": {
			"audioSoundField": "mono",
			"numberOfAudioTracks": 1
		},
		"notes": {
			"physicalConditionPreShipNotes": "cassette shows XYZ damage",
			"physicalConditionDigitizationNotes": "tape shows ABC damage"
		}
	},
	"digitizationProcess": {
		"playbackDevice": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer B",
			"model": "Model XYZ"
		},
		"timeBaseCorrector": {
			"id": "id12345",
			"serialNumber": 12345,
      "manufacturer": "Manufacturer C",
      "model": "Model XYZ"
		},
		"analogDigitalConverter" : {
      "id": "id12345",
      "serialNumber": "id12345abc",
      "manufacturer": "Manufacturere D",
      "model": "Model XYZ"
		},
		"analogDigitalConverter": {
			"serialNumber": "xyz123",
			"manufacturer": "Manufacturer D",
			"model": "Model XYZ"
		},
		"captureSoftware": {
			"manufacturer": "Manufacturer E",
			"productName": "Product XYZ",
			"version": "Version 123",
			"platform": "OS XYZ"
		},
		"notes": {
			"processNotes": "required intervention for reason xyz"
		}
	},
	"digitizer": {
		"operator": {
			"firstName": "Doe",
			"lastName": "Jane"
		},
		"organization": {
			"name": "Organization XYZ",
			"addressStreet1": "123 ABC St",
			"addressStreet2": "Suite 1234",
			"addressCity": "Anytown",
			"addressState": "ST",
			"addressPostalCode": "12345"
		}
	}
}
